### ISSUE TITLE
首次使用插件的时候下载的东西存到哪里去了？

### ISSUE THREAD

**Issue by TCOTC** [byname1234/siyuan-plugin-note-to-website#2]
我 C 盘莫名其妙满了，想了想怀疑是插件的问题

**Comment by byname4321** [comment]
> 我 C 盘莫名其妙满了，想了想怀疑是插件的问题

本插件自动下载的内容，和生成的内容会放在相应工作区目录下的 temp/siyuan-to-website 目录下。例如：当前的工作区路径为C:\Users\xx\siyuan-vault，则本插件相关的内容全部放在 C:\Users\xx\siyuan-vault\temp\siyuan-to-website 下，siyuan-to-website目录下的pvenv可能会比较大，它是基础环境，可以将pvenv删除，也可以将siyuan-to-website整个目录删除，不过，最好保留pvenv目录，因为插件工作要依赖于它，若将其删除，在生成html时，就会重新下载一遍，比较耗时。
